### ISSUE TITLE
can't see issues

### ISSUE THREAD

**Issue by prev767** [7yl4r/test-repository-2022-usf-github-101#1]
delay in viewing issues

**Comment by 7yl4r** [comment]
Aha! Thank you for opening this issue because I now see what happened.

The repo the rest of us were using yesterday is over at https://github.com/7yl4r/github-lessons-usf/issues

This is the repo I created as a demo but I linked to that other one in the presentation. I probably should have given this demo repo a less similar name.

**Comment by prev767** [comment]
Hi Tylar, Thanks for clarifying!

-Luanna
________________________________
